const quotes = [
    "Eu acredito no amor. Eu creio que pode existir alguma chance e eu sempre acho que pode ser diferente. Talvez essa seja a explicação de todas decepções.",
    "Creio no riso e nas lágrimas como antídotos contra o ódio e o terror.",
    "Seja como for o que penses, creio que é melhor dizê-lo com boas palavras.",
    "Eu creio que um dos princípios essenciais da sabedoria é o de se abster das ameaças verbais ou insultos.",
    "Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado.",
    "O importante não é aquilo que fazem de nós, mas o que nós mesmos fazemos do que os outros fizeram de nós.",
    "Quando eu estava com ele, o tempo e o espaço eram tão escorregadios que eu acabava perdendo a noção dos dois.",
    "Aprenda com os erros dos outros. Você não consegue viver tempo suficiente para cometer todos por si mesmo.",
    "A mente que se abre a uma nova ideia jamais voltará ao seu tamanho original.",
    "Há três coisas na vida que nunca voltam atrás: a flecha lançada, a palavra pronunciada e a oportunidade perdida.",
    "Não ganhe o mundo e perca sua alma; sabedoria é melhor que prata e ouro.",
    "O próprio viver é morrer, porque não temos um dia a mais na nossa vida que não tenhamos, nisso, um dia a menos nela.",
    "Você é a coisa mais importante para mim agora. A coisa mais importante para mim para sempre.",
    "Eu gosto da noite. Sem a escuridão, não poderíamos ver as estrelas.",
    "As convicções são inimigas mais perigosas da verdade do que as mentiras.",
    "Não lamente o que podia ter e se perdeu por caminhos errados e nunca mais voltou.",
    "As pessoas mais perigosas são aquelas que têm paixão, mas não têm sabedoria.",
    "A vida me ensinou a nunca desistir. Nem ganhar, nem perder, mas procurar evoluir.",
    "Você realmente tem alguma ideia do quanto é importante para mim? Algum conceito do quanto eu te amo?",
    "O porto é o lugar mais seguro para um barco, mas ele não foi feito para ficar lá; seu destino é navegar."
];
